// Generated by using torchexport::export() -> do not edit by hand
#include "exports.h"
#define IGNITE_HEADERS_ONLY
#include <ignite/ignite.h>

// [[Rcpp::export]]
ignite::adamw_param_groups rcpp_ignite_adamw_get_param_groups (ignite::optim_adamw groups) {
  return  ignite_adamw_get_param_groups(groups.get());
}
// [[Rcpp::export]]
int rcpp_ignite_adamw_param_groups_size (ignite::optim_param_groups groups) {
  return  ignite_adamw_param_groups_size(groups.get());
}
// [[Rcpp::export]]
torch::TensorList rcpp_ignite_optim_get_param_group_params (ignite::optim_param_groups groups, int i) {
  return  ignite_optim_get_param_group_params(groups.get(), i);
}
// [[Rcpp::export]]
torch::TensorList rcpp_ignite_adamw_get_states (ignite::optim_adamw opt) {
  return  ignite_adamw_get_states(opt.get());
}
// [[Rcpp::export]]
void rcpp_ignite_adamw_set_states (ignite::optim_adamw opt, torch::TensorList states) {
   ignite_adamw_set_states(opt.get(), states.get());
}
// [[Rcpp::export]]
torch::TensorList rcpp_ignite_opt_step (Rcpp::XPtr<XPtrTorchScriptModule> network, Rcpp::XPtr<XPtrTorchScriptModule> loss_fn, XPtrTorchStack input, torch::Tensor target, ignite::optim_adamw optimizer) {
  return  ignite_opt_step(network.get(), loss_fn.get(), input.get(), target.get(), optimizer.get());
}
// [[Rcpp::export]]
torch::Tensor rcpp_ignite_predict_step (Rcpp::XPtr<XPtrTorchScriptModule> network, XPtrTorchStack input) {
  return  ignite_predict_step(network.get(), input.get());
}
// [[Rcpp::export]]
ignite::optim_adamw rcpp_ignite_adamw (torch::TensorList params, double lr, double beta1, double beta2, double eps, double weight_decay, bool amsgrad) {
  return  ignite_adamw(params.get(), lr, beta1, beta2, eps, weight_decay, amsgrad);
}
// [[Rcpp::export]]
void rcpp_ignite_adamw_step (ignite::optim_adamw opt) {
   ignite_adamw_step(opt.get());
}
// [[Rcpp::export]]
void rcpp_ignite_adamw_zero_grad (ignite::optim_adamw opt) {
   ignite_adamw_zero_grad(opt.get());
}
// [[Rcpp::export]]
void rcpp_delete_optim (void* x) {
   delete_optim(x);
}
// [[Rcpp::export]]
void rcpp_delete_optim_sgd (void* x) {
   delete_optim_sgd(x);
}
// [[Rcpp::export]]
void rcpp_delete_optim_adam (void* x) {
   delete_optim_adam(x);
}
// [[Rcpp::export]]
void rcpp_delete_optim_adamw (void* x) {
   delete_optim_adamw(x);
}
// [[Rcpp::export]]
void rcpp_delete_optim_adagrad (void* x) {
   delete_optim_adagrad(x);
}
// [[Rcpp::export]]
void rcpp_delete_optim_rmsprop (void* x) {
   delete_optim_rmsprop(x);
}
// [[Rcpp::export]]
void rcpp_delete_optim_param_groups (void* x) {
   delete_optim_param_groups(x);
}
// [[Rcpp::export]]
void rcpp_delete_optim_param_group (void* x) {
   delete_optim_param_group(x);
}
// [[Rcpp::export]]
void rcpp_delete_adamw_param_group (void* x) {
   delete_adamw_param_group(x);
}
// [[Rcpp::export]]
void rcpp_delete_adamw_state (void* x) {
   delete_adamw_state(x);
}
// [[Rcpp::export]]
void rcpp_delete_adamw_options (void* x) {
   delete_adamw_options(x);
}
