# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_ignite_sgd_get_param_groups <- function(opt) {
    .Call('_ignite_rcpp_ignite_sgd_get_param_groups', PACKAGE = 'ignite', opt)
}

rcpp_ignite_sgd_set_param_groups <- function(opt, param_groups) {
    invisible(.Call('_ignite_rcpp_ignite_sgd_set_param_groups', PACKAGE = 'ignite', opt, param_groups))
}

rcpp_ignite_adamw_get_param_groups <- function(opt) {
    .Call('_ignite_rcpp_ignite_adamw_get_param_groups', PACKAGE = 'ignite', opt)
}

rcpp_ignite_adamw_set_param_groups <- function(opt, param_groups) {
    invisible(.Call('_ignite_rcpp_ignite_adamw_set_param_groups', PACKAGE = 'ignite', opt, param_groups))
}

rcpp_ignite_adamw_state <- function(opt) {
    .Call('_ignite_rcpp_ignite_adamw_state', PACKAGE = 'ignite', opt)
}

rcpp_ignite_opt_step <- function(network, loss_fn, input, target, optimizer) {
    .Call('_ignite_rcpp_ignite_opt_step', PACKAGE = 'ignite', network, loss_fn, input, target, optimizer)
}

rcpp_ignite_predict_step <- function(network, input) {
    .Call('_ignite_rcpp_ignite_predict_step', PACKAGE = 'ignite', network, input)
}

rcpp_ignite_sgd <- function(params, lr, momentum, dampening, weight_decay, nesterov) {
    .Call('_ignite_rcpp_ignite_sgd', PACKAGE = 'ignite', params, lr, momentum, dampening, weight_decay, nesterov)
}

rcpp_ignite_sgd_step <- function(opt) {
    invisible(.Call('_ignite_rcpp_ignite_sgd_step', PACKAGE = 'ignite', opt))
}

rcpp_ignite_sgd_zero_grad <- function(opt) {
    invisible(.Call('_ignite_rcpp_ignite_sgd_zero_grad', PACKAGE = 'ignite', opt))
}

rcpp_ignite_adam <- function(params, lr, beta1, beta2, eps, weight_decay, amsgrad) {
    .Call('_ignite_rcpp_ignite_adam', PACKAGE = 'ignite', params, lr, beta1, beta2, eps, weight_decay, amsgrad)
}

rcpp_ignite_adam_step <- function(opt) {
    invisible(.Call('_ignite_rcpp_ignite_adam_step', PACKAGE = 'ignite', opt))
}

rcpp_ignite_adam_zero_grad <- function(opt) {
    invisible(.Call('_ignite_rcpp_ignite_adam_zero_grad', PACKAGE = 'ignite', opt))
}

rcpp_ignite_adamw <- function(groups) {
    .Call('_ignite_rcpp_ignite_adamw', PACKAGE = 'ignite', groups)
}

rcpp_ignite_adamw_step <- function(opt) {
    invisible(.Call('_ignite_rcpp_ignite_adamw_step', PACKAGE = 'ignite', opt))
}

rcpp_ignite_adamw_zero_grad <- function(opt) {
    invisible(.Call('_ignite_rcpp_ignite_adamw_zero_grad', PACKAGE = 'ignite', opt))
}

rcpp_ignite_adagrad <- function(params, lr, lr_decay, weight_decay, initial_accumulator_value, eps) {
    .Call('_ignite_rcpp_ignite_adagrad', PACKAGE = 'ignite', params, lr, lr_decay, weight_decay, initial_accumulator_value, eps)
}

rcpp_ignite_adagrad_step <- function(opt) {
    invisible(.Call('_ignite_rcpp_ignite_adagrad_step', PACKAGE = 'ignite', opt))
}

rcpp_ignite_adagrad_zero_grad <- function(opt) {
    invisible(.Call('_ignite_rcpp_ignite_adagrad_zero_grad', PACKAGE = 'ignite', opt))
}

rcpp_ignite_rmsprop <- function(params, lr, alpha, eps, weight_decay, momentum, centered) {
    .Call('_ignite_rcpp_ignite_rmsprop', PACKAGE = 'ignite', params, lr, alpha, eps, weight_decay, momentum, centered)
}

rcpp_ignite_rmsprop_step <- function(opt) {
    invisible(.Call('_ignite_rcpp_ignite_rmsprop_step', PACKAGE = 'ignite', opt))
}

rcpp_ignite_rmsprop_zero_grad <- function(opt) {
    invisible(.Call('_ignite_rcpp_ignite_rmsprop_zero_grad', PACKAGE = 'ignite', opt))
}

rcpp_delete_optim_sgd <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_optim_sgd', PACKAGE = 'ignite', x))
}

rcpp_delete_optim_adam <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_optim_adam', PACKAGE = 'ignite', x))
}

rcpp_delete_optim_adamw <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_optim_adamw', PACKAGE = 'ignite', x))
}

rcpp_delete_optim_adagrad <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_optim_adagrad', PACKAGE = 'ignite', x))
}

rcpp_delete_optim_rmsprop <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_optim_rmsprop', PACKAGE = 'ignite', x))
}

rcpp_delete_optim_param_groups <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_optim_param_groups', PACKAGE = 'ignite', x))
}

rcpp_delete_optim_param_group <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_optim_param_group', PACKAGE = 'ignite', x))
}

rcpp_delete_sgd_param_groups <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_sgd_param_groups', PACKAGE = 'ignite', x))
}

rcpp_delete_sgd_param_group <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_sgd_param_group', PACKAGE = 'ignite', x))
}

rcpp_delete_adamw_param_groups <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_adamw_param_groups', PACKAGE = 'ignite', x))
}

rcpp_delete_adamw_param_group <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_adamw_param_group', PACKAGE = 'ignite', x))
}

rcpp_delete_adamw_states <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_adamw_states', PACKAGE = 'ignite', x))
}

ignite_raise_exception <- function() {
    invisible(.Call('_ignite_ignite_raise_exception', PACKAGE = 'ignite'))
}

