# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_ignite_sgd <- function(params, lr, momentum, dampening, weight_decay, nesterov) {
    .Call('_ignite_rcpp_ignite_sgd', PACKAGE = 'ignite', params, lr, momentum, dampening, weight_decay, nesterov)
}

rcpp_ignite_sgd_step <- function(opt) {
    invisible(.Call('_ignite_rcpp_ignite_sgd_step', PACKAGE = 'ignite', opt))
}

rcpp_ignite_sgd_zero_grad <- function(opt) {
    invisible(.Call('_ignite_rcpp_ignite_sgd_zero_grad', PACKAGE = 'ignite', opt))
}

rcpp_ignite_run_script_module <- function(network, loss_fn, input, target, optimizer) {
    .Call('_ignite_rcpp_ignite_run_script_module', PACKAGE = 'ignite', network, loss_fn, input, target, optimizer)
}

rcpp_ignite_forward <- function(input, weights, bias, old_h, old_cell) {
    .Call('_ignite_rcpp_ignite_forward', PACKAGE = 'ignite', input, weights, bias, old_h, old_cell)
}

rcpp_ignite_backward <- function(grad_h, grad_cell, new_cell, input_gate, output_gate, candidate_cell, X, gate_weights, weights) {
    .Call('_ignite_rcpp_ignite_backward', PACKAGE = 'ignite', grad_h, grad_cell, new_cell, input_gate, output_gate, candidate_cell, X, gate_weights, weights)
}

rcpp_delete_optim_sgd <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_optim_sgd', PACKAGE = 'ignite', x))
}

rcpp_delete_graph_function <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_graph_function', PACKAGE = 'ignite', x))
}

rcpp_delete_script_module2 <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_script_module2', PACKAGE = 'ignite', x))
}

rcpp_delete_stack2 <- function(x) {
    invisible(.Call('_ignite_rcpp_delete_stack2', PACKAGE = 'ignite', x))
}

ignite_raise_exception <- function() {
    invisible(.Call('_ignite_ignite_raise_exception', PACKAGE = 'ignite'))
}

